In [137]:
#import 
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
import xgboost as xgb
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RandomizedSearchCV
from sklearn.preprocessing import StandardScaler

In [140]:
df = pd.read_csv('C:/Users/nazar/Tennis_Match_Prediction/data/processed_data/simple_model_dataset_50_50.csv')

In [139]:
df.head()

draw_size  match_num  winner_ht  winner_age  loser_ht  loser_age  \
0        128        171      191.0        20.6     193.0       22.0   
1         32         30      180.0        25.2     175.0       31.8   
2        128       1133      193.0        20.7     191.0       23.9   
3        128         30      190.0        26.1     190.0       31.9   
4         16        261      206.0        36.6     193.0       26.5   

   winner_rank  winner_rank_points  loser_rank  loser_rank_points  ...  \
0         53.0               879.0         8.0             3625.0  ...   
1         54.0               860.0         4.0             5440.0  ...   
2          6.0              4080.0       116.0              493.0  ...   
3         36.0              1125.0       216.0              226.0  ...   
4         24.0              1991.0       238.0              264.0  ...   

   winner_hand_R  winner_hand_U  tourney_level_A  tourney_level_D  \
0              0              0                0                0   
1              1              0                1                0   
2              1              0                0                0   
3              0              0                0                0   
4              1              0                1                0   

   tourney_level_F  tourney_level_G  tourney_level_M  loser_hand_L  \
0                0                1                0             0   
1                0                0                0             0   
2                0                1                0             1   
3                0                1                0             0   
4                0                0                0             0   

   loser_hand_R  loser_hand_U  
0             1             0  
1             1             0  
2             0             0  
3             1             0  
4             1             0  

[5 rows x 26 columns]

In [104]:
#creating y and X

In [105]:
y = df['target']
X =df.drop('target',axis = 1)

In [106]:
#split data
X_train, X_valid, y_train, y_valid = train_test_split(X,y,test_size = 0.3, random_state = 17)

In [107]:
X_train.shape, X_valid.shape

((25044, 25), (10734, 25))

In [108]:
#distribution of target 
len(df[df['target' ]==1])/len(df['target'])

0.49963664821957626

In [109]:
#create a Decision Tree model
clf = DecisionTreeClassifier(random_state = 17)

In [110]:
#cross validation
np.mean(cross_val_score(clf,X_train,y_train, cv= 5 ))

0.5002393136443859

In [146]:
#parameters for tree
tree_params = {'max_depth':np.arange(1,11),'max_features':[0.5,0.7,1]}

In [147]:
#looking for the best params
tree_grid = GridSearchCV(clf, tree_params, cv = 5, n_jobs = -1)

In [148]:
%%time
tree_grid.fit(X_train,y_train);

CPU times: total: 656 ms
Wall time: 3.28 s


In [145]:
tree_grid.best_score_, tree_grid.best_params_

(0.5033142659506817, {'max_depth': 5, 'max_features': 0.5})

In [114]:
tree_valid_pred = tree_grid.predict(X_valid)

In [115]:
accuracy = accuracy_score(y_valid, tree_valid_pred)

In [116]:
accuracy

0.4936649897521893

In [117]:
confusion_matrix(y_valid, tree_valid_pred)

array([[ 940, 4463],
       [ 972, 4359]], dtype=int64)

In [118]:
#model predicts only tartet 1

In [119]:
#find best model
for i in range(1,25):
    clf_1=DecisionTreeClassifier(max_depth = i)
    clf_1.fit(X_train,y_train)
    y_pred_clf = clf_1.predict(X_valid)
    print(f'DecisonTreeClassifier with max_depth {i}')
    print(f'Accuracy : {accuracy_score(y_valid,y_pred_clf)}')
    print(confusion_matrix(y_valid,y_pred_clf))



DecisonTreeClassifier with max_depth 1
Accuracy : 0.4945966089062791
[[ 885 4518]
 [ 907 4424]]
DecisonTreeClassifier with max_depth 2
Accuracy : 0.4942239612446432
[[ 936 4467]
 [ 962 4369]]
DecisonTreeClassifier with max_depth 3
Accuracy : 0.49552822806036895
[[ 913 4490]
 [ 925 4406]]
DecisonTreeClassifier with max_depth 4
Accuracy : 0.49357182783678033
[[ 846 4557]
 [ 879 4452]]
DecisonTreeClassifier with max_depth 5
Accuracy : 0.4936649897521893
[[ 838 4565]
 [ 870 4461]]
DecisonTreeClassifier with max_depth 6
Accuracy : 0.4946897708216881
[[ 772 4631]
 [ 793 4538]]
DecisonTreeClassifier with max_depth 7
Accuracy : 0.4956213899757779
[[ 854 4549]
 [ 865 4466]]
DecisonTreeClassifier with max_depth 8
Accuracy : 0.4965530091298677
[[ 837 4566]
 [ 838 4493]]
DecisonTreeClassifier with max_depth 9
Accuracy : 0.49972051425377306
[[ 716 4687]
 [ 683 4648]]
DecisonTreeClassifier with max_depth 10
Accuracy : 0.49850940935345633
[[1008 4395]
 [ 988 4343]]
DecisonTreeClassifier with max_dept

In [120]:
clf_simple = DecisionTreeClassifier()

In [121]:
clf_simple.fit(X_train,y_train)

DecisionTreeClassifier()

In [122]:
clf_simple_pred = clf_simple.predict(X_valid)

In [123]:
accuracy_score(y_valid,clf_simple_pred)

0.49590087572200486

In [124]:
confusion_matrix(y_valid,clf_simple_pred)

array([[2699, 2704],
       [2707, 2624]], dtype=int64)

In [125]:
#DecisonTreeClassifier with max_depth 11
#Accuracy : 0.5053102291783119 - best model

In [126]:
# set up max_depth for tree

In [127]:
tree_params = {'max_depth':np.arange(1,11), 'max_features':[0.5,0.7,1]}

In [128]:
tree_grid = GridSearchCV(clf,tree_params, cv = 5, n_jobs = -1)

In [129]:
tree_grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=17), n_jobs=-1,
             param_grid={'max_depth': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
                         'max_features': [0.5, 0.7, 1]})

In [130]:
tree_grid.best_score_, tree_grid.best_params_

(0.5033142659506817, {'max_depth': 5, 'max_features': 0.5})

In [131]:
clf_1 = DecisionTreeClassifier(max_depth = 5, max_features = 0.5,random_state = 17)

In [132]:
clf_1.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=5, max_features=0.5, random_state=17)

In [133]:
tree_valid_pred_1 = clf_1.predict(X_valid)

In [134]:
accuracy_score(y_valid,tree_valid_pred_1 )

0.4936649897521893

In [135]:
confusion_matrix(y_valid, tree_valid_pred_1)

array([[ 940, 4463],
       [ 972, 4359]], dtype=int64)

In [136]:
#fit model with LogistcRegression

In [109]:
# Define model


scaler = StandardScaler()
X_train_skaler = scaler.fit_transform(X_train)
X_valid_skaler = scaler.transform(X_valid)


model = LogisticRegression()


# define search space
param_grid = {
    'C' : np.logspace(0, 4, num=10),
    'penalty' : ['l1', 'l2'],
    'solver' : ['liblinear', 'sag']
}

search = RandomizedSearchCV(model, param_grid, n_iter=5, cv=10, scoring='accuracy', n_jobs=-1, random_state=1)

# execute search
result = search.fit(X_train_skaler, y_train)
# summarize result
print('Best Score: %s' % result.best_score_)
print('Best Hyperparameters: %s' % result.best_params_)

C:\Users\nazar\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning: 
10 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\nazar\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\nazar\anaconda3\Lib\site-packages\sklearn\base.py", line 1151, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nazar\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1168, in fit
    solver = _

Best Score: 0.5009573504747692
Best Hyperparameters: {'solver': 'sag', 'penalty': 'l2', 'C': 1.0}


C:\Users\nazar\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


In [70]:
model_LR = LogisticRegression(n_jobs = -1,random_state = 17)

In [71]:
model_LR.fit(X_train, y_train)

LogisticRegression(n_jobs=-1, random_state=17)

In [72]:
LR_pred = model_LR.predict(X_valid)

In [73]:
accuracy_score(y_valid,LR_pred )

0.4924538848518726

In [74]:
confusion_matrix(y_valid, LR_pred)

array([[1818, 3585],
       [1863, 3468]], dtype=int64)

In [77]:
C = 1e-2

In [78]:
logit = LogisticRegression(C=C,n_jobs=-1,random_state = 17)

In [79]:
logit.fit(X_train,y_train)

LogisticRegression(C=0.01, n_jobs=-1, random_state=17)

In [80]:
logit_pred = model_LR.predict(X_valid)

In [81]:
accuracy_score(y_valid,logit_pred )

0.4924538848518726

In [82]:
confusion_matrix(y_valid, logit_pred)

array([[1818, 3585],
       [1863, 3468]], dtype=int64)

In [89]:
#fit ensemble model

In [90]:
model = xgb.XGBClassifier(n_estimators = 100, max_depth = 3, learning_rate = 0.1)

In [91]:
model.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [92]:
y_pred_xgb = model.predict(X_valid)

In [93]:
accuracy_score(y_valid,y_pred_xgb )

0.49878889509968327

In [94]:
confusion_matrix(y_valid, y_pred_xgb)

array([[2384, 3019],
       [2361, 2970]], dtype=int64)

In [95]:
#fit with Random Forest

In [96]:
rf_model = RandomForestClassifier(n_estimators = 100)

In [97]:
rf_model.fit(X_train, y_train)

RandomForestClassifier()

In [98]:
y_pred_rf = rf_model.predict(X_valid)

In [99]:
accuracy_score(y_valid,y_pred_rf )

0.4990683808459102

In [100]:
confusion_matrix(y_valid, y_pred_rf)

array([[2760, 2643],
       [2734, 2597]], dtype=int64)

In [101]:
#fit with SVC

In [102]:
svm_model = SVC(kernel = 'linear')

In [103]:
svm_model.fit(X_train, y_train)

SVC(kernel='linear')

In [110]:
y_pred_svm = svm_model.predict(X_valid) 

In [111]:
accuracy_score(y_valid,y_pred_svm )

0.4920812371902366

In [112]:
confusion_matrix(y_valid, y_pred_svm)

array([[3150, 2253],
       [3199, 2132]], dtype=int64)

In [64]:
##using catboost

In [65]:
pip install catboost

  Obtaining dependency information for catboost from https://files.pythonhosted.org/packages/e2/63/379617e3d982e8a66c9d66ebf4621d3357c7c18ad356473c335bffd5aba6/catboost-1.2.2-cp311-cp311-win_amd64.whl.metadata
     ---------------------------------------- 0.0/47.0 kB ? eta -:--:--
     --------------------------------- ---- 41.0/47.0 kB 991.0 kB/s eta 0:00:01
     -------------------------------------- 47.0/47.0 kB 593.5 kB/s eta 0:00:00
   ---------------------------------------- 0.0/101.0 MB ? eta -:--:--
   ---------------------------------------- 0.1/101.0 MB 2.6 MB/s eta 0:00:39
   ---------------------------------------- 0.2/101.0 MB 2.0 MB/s eta 0:00:52
   ---------------------------------------- 0.3/101.0 MB 2.5 MB/s eta 0:00:40
   ---------------------------------------- 0.4/101.0 MB 2.5 MB/s eta 0:00:41
   ---------------------------------------- 0.6/101.0 MB 2.9 MB/s eta 0:00:35
   ---------------------------------------- 0.7/101.0 MB 2.6 MB/s eta 0:00:39
   ----------------

In [66]:
from catboost import CatBoostClassifier

In [95]:
model_catboost = CatBoostClassifier(iterations=100, learning_rate=0.1, depth=6, loss_function='Logloss', cat_features=[0, 1, 2])


In [96]:
model_catboost.fit(X_train,y_train)

0:	learn: 0.6929311	total: 43.3ms	remaining: 4.29s
1:	learn: 0.6927102	total: 86.4ms	remaining: 4.24s
2:	learn: 0.6926075	total: 132ms	remaining: 4.26s
3:	learn: 0.6924188	total: 178ms	remaining: 4.27s
4:	learn: 0.6922849	total: 225ms	remaining: 4.26s
5:	learn: 0.6921320	total: 273ms	remaining: 4.28s
6:	learn: 0.6920159	total: 327ms	remaining: 4.34s
7:	learn: 0.6918976	total: 372ms	remaining: 4.28s
8:	learn: 0.6916598	total: 417ms	remaining: 4.21s
9:	learn: 0.6915417	total: 462ms	remaining: 4.16s
10:	learn: 0.6913850	total: 512ms	remaining: 4.14s
11:	learn: 0.6913327	total: 557ms	remaining: 4.09s
12:	learn: 0.6911197	total: 618ms	remaining: 4.13s
13:	learn: 0.6910379	total: 666ms	remaining: 4.09s
14:	learn: 0.6908854	total: 716ms	remaining: 4.05s
15:	learn: 0.6908195	total: 767ms	remaining: 4.03s
16:	learn: 0.6906941	total: 818ms	remaining: 3.99s
17:	learn: 0.6905643	total: 865ms	remaining: 3.94s
18:	learn: 0.6904649	total: 911ms	remaining: 3.88s
19:	learn: 0.6903686	total: 964ms	remai

In [97]:
X_train[['winner_ht','winner_age','winner_rank','winner_rank_points','loser_ht','loser_age','loser_rank','loser_rank_points']] = X_train[['winner_ht','winner_age','winner_rank','winner_rank_points','loser_ht','loser_age','loser_rank','loser_rank_points']].astype(int)


In [98]:
X_valid.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7156 entries, 25086 to 25330
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   draw_size           7156 non-null   int64
 1   match_num           7156 non-null   int64
 2   winner_ht           7156 non-null   int32
 3   winner_age          7156 non-null   int32
 4   loser_ht            7156 non-null   int32
 5   loser_age           7156 non-null   int32
 6   winner_rank         7156 non-null   int32
 7   winner_rank_points  7156 non-null   int32
 8   loser_rank          7156 non-null   int32
 9   loser_rank_points   7156 non-null   int32
 10  surface_Carpet      7156 non-null   int64
 11  surface_Clay        7156 non-null   int64
 12  surface_Grass       7156 non-null   int64
 13  surface_Hard        7156 non-null   int64
 14  winner_hand_L       7156 non-null   int64
 15  winner_hand_R       7156 non-null   int64
 16  winner_hand_U       7156 non-null   i

In [99]:
X_valid[['winner_ht','winner_age','winner_rank','winner_rank_points','loser_ht','loser_age','loser_rank','loser_rank_points']] = X_valid[['winner_ht','winner_age','winner_rank','winner_rank_points','loser_ht','loser_age','loser_rank','loser_rank_points']].replace([np.inf, -np.inf], np.iinfo(np.int32).max).fillna(0).astype(int)


In [100]:
pred = model_catboost.predict(X_valid)

In [101]:
accuracy_score(y_valid,pred)

0.4986025712688653

In [102]:
confusion_matrix(y_valid,pred)

array([[2913,  724],
       [2864,  655]], dtype=int64)